// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Account struct {
	ID         int64
	Name       string
	CurrencyID int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

type AppMetum struct {
	Key   string
	Value string
}

type Balance struct {
	ID        int64
	AccountID int64
	Date      string
	Amount    int64
	Scale     int64
	Notes     string
	CreatedAt string
	UpdatedAt string
}

type Currency struct {
	ID        int64
	Code      string
	Name      string
	Scale     int64
	CreatedAt string
	UpdatedAt string
}

type CurrencyRate struct {
	ID              int64
	CurrencyID      int64
	RateToUsdAmount int64
	RateToUsdScale  int64
	UpdatedAt       string
}

type History struct {
	ID        int64
	Timestamp string
	Action    string
	Path      string
	OldData   sql.NullString
	NewData   sql.NullString
}
