// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const countBalancesByAccountID = `-- name: CountBalancesByAccountID :one
SELECT count(*) FROM balances WHERE account_id = ?
`

func (q *Queries) CountBalancesByAccountID(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBalancesByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :execresult

INSERT INTO accounts (name, currency_id, on_budget, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	Name       string
	CurrencyID int64
	OnBudget   int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

// Accounts
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount,
		arg.Name,
		arg.CurrencyID,
		arg.OnBudget,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createBalance = `-- name: CreateBalance :execresult

INSERT INTO balances (account_id, date, amount, scale, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateBalanceParams struct {
	AccountID int64
	Date      string
	Amount    int64
	Scale     int64
	Notes     string
	CreatedAt string
	UpdatedAt string
}

// Balances
func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBalance,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.Scale,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createHistory = `-- name: CreateHistory :execresult

INSERT INTO history (timestamp, action, path, old_data, new_data)
VALUES (?, ?, ?, ?, ?)
`

type CreateHistoryParams struct {
	Timestamp string
	Action    string
	Path      string
	OldData   sql.NullString
	NewData   sql.NullString
}

// History
func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHistory,
		arg.Timestamp,
		arg.Action,
		arg.Path,
		arg.OldData,
		arg.NewData,
	)
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteBalance = `-- name: DeleteBalance :exec
DELETE FROM balances WHERE id = ?
`

func (q *Queries) DeleteBalance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBalance, id)
	return err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
  a.id,
  a.name,
  a.currency_id,
  c.code,
  c.scale,
  a.on_budget,
  a.hidden,
  a.notes,
  a.created_at,
  a.updated_at
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
WHERE a.id = ?
`

type GetAccountByIDRow struct {
	ID         int64
	Name       string
	CurrencyID int64
	Code       string
	Scale      int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Code,
		&i.Scale,
		&i.OnBudget,
		&i.Hidden,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT
  a.id,
  a.name,
  a.currency_id,
  c.code,
  c.scale,
  a.on_budget,
  a.hidden,
  a.notes,
  a.created_at,
  a.updated_at
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
WHERE a.name = ?
`

type GetAccountByNameRow struct {
	ID         int64
	Name       string
	CurrencyID int64
	Code       string
	Scale      int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) GetAccountByName(ctx context.Context, name string) (GetAccountByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByName, name)
	var i GetAccountByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Code,
		&i.Scale,
		&i.OnBudget,
		&i.Hidden,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppMetaApp = `-- name: GetAppMetaApp :one

SELECT value FROM app_meta WHERE key = 'app'
`

// Startup / meta
func (q *Queries) GetAppMetaApp(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppMetaApp)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getBalanceByAccountDate = `-- name: GetBalanceByAccountDate :one
SELECT id, account_id, date, amount, scale, notes, created_at, updated_at
FROM balances
WHERE account_id = ? AND date = ?
`

type GetBalanceByAccountDateParams struct {
	AccountID int64
	Date      string
}

func (q *Queries) GetBalanceByAccountDate(ctx context.Context, arg GetBalanceByAccountDateParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalanceByAccountDate, arg.AccountID, arg.Date)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.Scale,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceByID = `-- name: GetBalanceByID :one
SELECT id, account_id, date, amount, scale, notes, created_at, updated_at
FROM balances
WHERE id = ?
`

func (q *Queries) GetBalanceByID(ctx context.Context, id int64) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalanceByID, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.Scale,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one

SELECT
  c.id,
  c.code,
  c.name,
  c.scale,
  cr.rate_to_usd_amount,
  cr.rate_to_usd_scale,
  cr.updated_at
FROM currencies c
LEFT JOIN currency_rates cr ON cr.currency_id = c.id
WHERE c.code = ?
`

type GetCurrencyByCodeRow struct {
	ID              int64
	Code            string
	Name            string
	Scale           int64
	RateToUsdAmount sql.NullInt64
	RateToUsdScale  sql.NullInt64
	UpdatedAt       sql.NullString
}

// Currencies
func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (GetCurrencyByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, code)
	var i GetCurrencyByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Scale,
		&i.RateToUsdAmount,
		&i.RateToUsdScale,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT
  c.id,
  c.code,
  c.name,
  c.scale,
  cr.rate_to_usd_amount,
  cr.rate_to_usd_scale,
  cr.updated_at
FROM currencies c
LEFT JOIN currency_rates cr ON cr.currency_id = c.id
WHERE c.id = ?
`

type GetCurrencyByIDRow struct {
	ID              int64
	Code            string
	Name            string
	Scale           int64
	RateToUsdAmount sql.NullInt64
	RateToUsdScale  sql.NullInt64
	UpdatedAt       sql.NullString
}

func (q *Queries) GetCurrencyByID(ctx context.Context, id int64) (GetCurrencyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByID, id)
	var i GetCurrencyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Scale,
		&i.RateToUsdAmount,
		&i.RateToUsdScale,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencyIDByCode = `-- name: GetCurrencyIDByCode :one
SELECT id FROM currencies WHERE code = ?
`

func (q *Queries) GetCurrencyIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLatestBalanceByAccount = `-- name: GetLatestBalanceByAccount :one
SELECT id, account_id, date, amount, scale, notes, created_at, updated_at
FROM balances
WHERE account_id = ?
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestBalanceByAccount(ctx context.Context, accountID int64) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getLatestBalanceByAccount, accountID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.Scale,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
  a.id,
  a.name,
  a.currency_id,
  c.code,
  c.scale,
  a.on_budget,
  a.hidden,
  a.notes,
  a.created_at,
  a.updated_at
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
ORDER BY a.name
`

type ListAccountsRow struct {
	ID         int64
	Name       string
	CurrencyID int64
	Code       string
	Scale      int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrencyID,
			&i.Code,
			&i.Scale,
			&i.OnBudget,
			&i.Hidden,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVisibleBalances = `-- name: ListAllVisibleBalances :many
SELECT
  a.id AS account_id,
  a.name AS account_name,
  a.currency_id,
  c.code,
  c.scale,
  a.on_budget,
  a.hidden,
  a.notes AS account_notes,
  a.created_at AS account_created_at,
  a.updated_at AS account_updated_at,
  b.id AS balance_id,
  b.account_id AS balance_account_id,
  b.date,
  b.amount,
  b.scale AS balance_scale,
  b.notes AS balance_notes,
  b.created_at AS balance_created_at,
  b.updated_at AS balance_updated_at
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
JOIN balances b ON b.account_id = a.id
WHERE a.hidden = 0
ORDER BY a.id, b.date
`

type ListAllVisibleBalancesRow struct {
	AccountID        int64
	AccountName      string
	CurrencyID       int64
	Code             string
	Scale            int64
	OnBudget         int64
	Hidden           int64
	AccountNotes     string
	AccountCreatedAt string
	AccountUpdatedAt string
	BalanceID        int64
	BalanceAccountID int64
	Date             string
	Amount           int64
	BalanceScale     int64
	BalanceNotes     string
	BalanceCreatedAt string
	BalanceUpdatedAt string
}

func (q *Queries) ListAllVisibleBalances(ctx context.Context) ([]ListAllVisibleBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllVisibleBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllVisibleBalancesRow
	for rows.Next() {
		var i ListAllVisibleBalancesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.CurrencyID,
			&i.Code,
			&i.Scale,
			&i.OnBudget,
			&i.Hidden,
			&i.AccountNotes,
			&i.AccountCreatedAt,
			&i.AccountUpdatedAt,
			&i.BalanceID,
			&i.BalanceAccountID,
			&i.Date,
			&i.Amount,
			&i.BalanceScale,
			&i.BalanceNotes,
			&i.BalanceCreatedAt,
			&i.BalanceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalancesByAccount = `-- name: ListBalancesByAccount :many
SELECT id, account_id, date, amount, scale, notes, created_at, updated_at
FROM balances
WHERE account_id = ?
ORDER BY date DESC
`

func (q *Queries) ListBalancesByAccount(ctx context.Context, accountID int64) ([]Balance, error) {
	rows, err := q.db.QueryContext(ctx, listBalancesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.Scale,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT
  c.id,
  c.code,
  c.name,
  c.scale,
  cr.rate_to_usd_amount,
  cr.rate_to_usd_scale,
  cr.updated_at
FROM currencies c
LEFT JOIN currency_rates cr ON cr.currency_id = c.id
ORDER BY c.code
`

type ListCurrenciesRow struct {
	ID              int64
	Code            string
	Name            string
	Scale           int64
	RateToUsdAmount sql.NullInt64
	RateToUsdScale  sql.NullInt64
	UpdatedAt       sql.NullString
}

func (q *Queries) ListCurrencies(ctx context.Context) ([]ListCurrenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrenciesRow
	for rows.Next() {
		var i ListCurrenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Scale,
			&i.RateToUsdAmount,
			&i.RateToUsdScale,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT id, timestamp, action, path, old_data, new_data
FROM history
ORDER BY timestamp, id
`

func (q *Queries) ListHistory(ctx context.Context) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Action,
			&i.Path,
			&i.OldData,
			&i.NewData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAccounts = `-- name: ListVisibleAccounts :many
SELECT
  a.id,
  a.name,
  a.currency_id,
  c.code,
  c.scale,
  a.on_budget,
  a.hidden,
  a.notes,
  a.created_at,
  a.updated_at
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
WHERE a.hidden = 0
ORDER BY a.name
`

type ListVisibleAccountsRow struct {
	ID         int64
	Name       string
	CurrencyID int64
	Code       string
	Scale      int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) ListVisibleAccounts(ctx context.Context) ([]ListVisibleAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleAccountsRow
	for rows.Next() {
		var i ListVisibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrencyID,
			&i.Code,
			&i.Scale,
			&i.OnBudget,
			&i.Hidden,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET name = ?, currency_id = ?, on_budget = ?, hidden = ?, notes = ?, updated_at = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Name       string
	CurrencyID int64
	OnBudget   int64
	Hidden     int64
	Notes      string
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.CurrencyID,
		arg.OnBudget,
		arg.Hidden,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE balances
SET date = ?, amount = ?, scale = ?, notes = ?, updated_at = ?
WHERE id = ?
`

type UpdateBalanceParams struct {
	Date      string
	Amount    int64
	Scale     int64
	Notes     string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateBalance,
		arg.Date,
		arg.Amount,
		arg.Scale,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertCurrency = `-- name: UpsertCurrency :exec

INSERT INTO currencies (code, name, scale, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (code) DO UPDATE SET
  name = excluded.name,
  scale = excluded.scale,
  updated_at = excluded.updated_at
`

type UpsertCurrencyParams struct {
	Code      string
	Name      string
	Scale     int64
	CreatedAt string
	UpdatedAt string
}

// Currency seeding
func (q *Queries) UpsertCurrency(ctx context.Context, arg UpsertCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrency,
		arg.Code,
		arg.Name,
		arg.Scale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCurrencyNameOnly = `-- name: UpsertCurrencyNameOnly :exec
INSERT INTO currencies (code, name, scale, created_at, updated_at)
VALUES (?, ?, 2, ?, ?)
ON CONFLICT (code) DO UPDATE SET name = excluded.name
`

type UpsertCurrencyNameOnlyParams struct {
	Code      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertCurrencyNameOnly(ctx context.Context, arg UpsertCurrencyNameOnlyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrencyNameOnly,
		arg.Code,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCurrencyRate = `-- name: UpsertCurrencyRate :exec
INSERT INTO currency_rates (currency_id, rate_to_usd_amount, rate_to_usd_scale, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (currency_id) DO UPDATE SET
  rate_to_usd_amount = excluded.rate_to_usd_amount,
  rate_to_usd_scale = excluded.rate_to_usd_scale,
  updated_at = excluded.updated_at
`

type UpsertCurrencyRateParams struct {
	CurrencyID      int64
	RateToUsdAmount int64
	RateToUsdScale  int64
	UpdatedAt       string
}

func (q *Queries) UpsertCurrencyRate(ctx context.Context, arg UpsertCurrencyRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrencyRate,
		arg.CurrencyID,
		arg.RateToUsdAmount,
		arg.RateToUsdScale,
		arg.UpdatedAt,
	)
	return err
}
